### ISSUE TITLE
Accessing the Headers object within the interceptor?

### ISSUE THREAD

**Issue by ropeladder** [vuejs/vue-resource#385]
With 1.0.0 the request object passed into the interceptor function no longer has access to the headers. How do I access (or assign) headers from within the interceptor function?

**Comment by steffans** [comment]
Yes, the request object has a `Request.headers` property which is a `Headers`object. You can use its `get` and `set` functions to modify the headers.

https://github.com/vuejs/vue-resource/blob/master/docs/api.md#headers

**Comment by ropeladder** [comment]
Oh ok--my previous code was overwriting the `Request.headers` object (and then no headers were being sent), so I didn't see that the object was being passed in.

Might be useful to add an example to the interceptor docs, e.g.:  
```
  // add headers
  request.headers.set('Authorization', 'Bearer: <jwt_token>')
```

**Comment by ropeladder** [comment]
Can you give a quick example of how to use it? The following is not working.

`request.headers.set('Authorization', 'Bearer: <jwt_token>')`

**Comment by callumacrae** [comment]
@ropeladder: Check the sent headers. Is it lowercasing them? Happening for us.

**Comment by devboxr** [comment]
Same here, we do the very thing you do above @ropeladder, and `1.0` broke it, because it converts the headers into lowercase (e.g. `authorization`). This is definitely a bug and needs urgent fixing.

**Comment by steffans** [comment]
Fixed this issue in v1.0.1

**Comment by mcordingley** [comment]
This appears to still happen in 1.0.1 (from CDNJS) when setting the header via "common":

`<script>Vue.http.headers.common['X-CSRF-TOKEN'] = '{{ csrf_token() }}';</script>`

Firebug reports this header/value pair on the request:

`x-csrf-token	EoIchtXIOODrmmnpM2MUdURbBVuonNTUcY9XvnCX`

Is it possible that the wrong version got sent to CDNJS? Or perhaps there's something else doing the lower-casing when the header comes in this way.
